version: '3.8'

services:
  # 을지대학교 을GPT API 서비스
  eulji-gpt-api:
    build: .
    container_name: eulji-gpt-api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - EULJI_GPT_ENV=production
      - EULJI_UNIVERSITY=을지대학교
      - EULJI_GPT_API_VERSION=1.0.0
      - EULJI_GPT_SECRET_KEY=${EULJI_GPT_SECRET_KEY:-eulji-gpt-production-key}
      - EULJI_GPT_DATABASE_URL=sqlite:///./eulji_gpt_production.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - eulji-gpt-network

  # 을지대학교 을GPT 프록시 (Nginx)
  nginx:
    image: nginx:alpine
    container_name: eulji-gpt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - eulji-gpt-api
    restart: unless-stopped
    networks:
      - eulji-gpt-network

# 네트워크 설정
networks:
  eulji-gpt-network:
    driver: bridge
